config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources "entries"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  validates :title, presence: true
  validates :contents, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all.order('date ASC')
  end

  def show
    @entry = Entry.find params[:id]
  end

  def new
  end

  def create
    entry_params = params["entry"].permit("title", :contents)
    entry = Entry.new(entry_params)
    if entry.save
      redirect_to(entry_path(entry))
      flash[:success] = "udało się"
    else
      render :new
    end
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def update
    entry_params = params[:entry].permit(:title, :contents)
    entry = Entry.find(params[:id])
    entry.update(entry_params)
    redirect_to(entry_path(entry))

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/edit.html.erb
<%= form_for(@entry) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title")%></p>
  <p><%= form.label("contents")%></p>
  <p><%= form.text_area("contents")%></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/index.html.erb
<ul>
  <% @entries.each do |entry| %>
  <h2><%= link_to(entry.title, entry_path(entry)) %></h2>
    <p><%= entry.date %></p>
    <p><%= entry.contents %></p>
  <% end %>
  
  <%= link_to("New entry", new_entry_path) %>
</ul>

app/views/entries/new.html.erb
<%= form_for(Entry.new) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title")%></p>
  <p><%= form.label("contents")%></p>
  <p><%= form.text_area("contents")%></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>  

app/views/entries/show.html.erb
<% if flash[:success] %>
   <div class="success"><%= flash[:success] %></div>
 <% end %>
<h2><%= @entry.title %></h2>
  <p><%= @entry.date %></p>
  <p><%= @entry.contents %></p>
  <p><%= link_to("Back to all entries", entries_path) %></p>
  <p><%= link_to("Edit this entry", edit_entry_path(@entry)) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>My Rails Girls Diary</h1>

        <%= yield %>

      <img src="http://railsgirls.com/images/rg-warsaw.png" />

  </body>
</html>

app/views/welcome/index.html.erb
<h2>Welcome</h2>
  <ul>
    <li><%= link_to "Show entries", entries_path %></li>
    <li>Archive</li>
  </ul>